library constants;

const String APP_BAR_TITLE = "Dashboard";
const String APP_BAR_WELCOME = "Bem vindo ao Pet São João";
const String APP_BAR_PET_LOVER = "Seja mais um Pet Lover";
const String APP_BAR_ISSUE = "Ops, estamos com problemas";
const String APP_BAR_LOADING = "Carregando...";
const String DRAWER_NAME = "José da Silva";
const String DRAWER_EMAIL = "jose.silva@gmail.com";
const String DRAWER_NAME_INITIAL = "J";
const String DRAWER_PROFILE = "Perfil";
const String DRAWER_SAVE_MY_PET = "Registrar meu pet";
const String DRAWER_FIND_A_PET = "Encontrei um pet";
const String DRAWER_LOGOUT = "Sair";
const String ACTION_CARD_TITLE = "Encontrei um pet";
const String ACTION_CARD_BODY = "Se você encontrou um pet perdido, tire algumas fotos dele e ajude-nos a salá-lo";
const String ACTION_CARD_BUTTON_TEXT = "ENCONTREI UM PET";
const String LOAD_DATA_ERROR = "Erro ao carregar os dados";
const String PETS_CARD_OPTION = "pets";
const String TUTORS_CARD_OPTION = "tutores";
const String PHOTOS_CARD_OPTION = "fotos";
const String ALERTS_CARD_OPTION = "alertas";
